[package]
name = "protobuf-deserialize-prost"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
bench-support = { path = "../../../../serialization/rust/bench-support" }
prost = "0.13"

[build-dependencies]
prost-build = "0.13"

[profile.release]
lto = true
codegen-units = 1
