[package]
name = "decompression-libdeflate"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bench-support = { path = "../../../../serialization/rust/bench-support" }
compression-bench-support = { path = "../../../../compression/rust/bench-support", features = ["libdeflate"] }

[profile.release]
lto = true
codegen-units = 1
