[package]
name = "compression-zlib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bench-support = { path = "../../../../serialization/rust/bench-support" }
compression-bench-support = { path = "../../../rust/bench-support", features = ["zlib"] }

[profile.release]
lto = true
codegen-units = 1
